---
sublime_text_configuration_directory: "/home/{{ desktop_user }}/.config/sublime-text-3"
sublime_text_installed_packages_directory: "{{ sublime_text_configuration_directory }}/Installed Packages"
sublime_text_user_package_configuration_directory: "{{ sublime_text_configuration_directory }}/Packages/User"
sublime_text_package_control_sha256_checksum: "6f4c264a24d933ce70df5dedcf1dcaeeebe013ee18cced0ef93d5f746d80ef60"