---
jetbrains_toolbox_version: "1.27.3.14493"
jetbrains_toolbox_download_url: "https://download.jetbrains.com/toolbox/jetbrains-toolbox-{{ jetbrains_toolbox_version }}.tar.gz"
jetbrains_toolbox_install_dir: "/opt/jetbrains-toolbox"
jetbrains_toolbox_bin: "{{ jetbrains_toolbox_install_dir }}/jetbrains-toolbox"
jetbrains_toolbox_plugins_dir: "{{ jetbrains_toolbox_install_dir }}/plugins"
jetbrains_toolbox_data_dir: "{{ jetbrains_toolbox_install_dir }}/data"
pycharm_version: "2022.3.2"
pycharm_download_url: "https://download-cf.jetbrains.com/python/pycharm-community-{{ pycharm_version }}.tar.gz"
pycharm_install_dir: "/opt/pycharm"
pycharm_bin: "{{ pycharm_install_dir }}/bin/pycharm.sh"
idea_version: "2022.3.2"
idea_download_url: "https://download-cf.jetbrains.com/idea/ideaIC-{{ idea_version }}.tar.gz"
idea_install_dir: "/opt/idea"
idea_bin: "{{ idea_install_dir }}/bin/idea.sh"